"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var jsx_runtime_1 = require("react/jsx-runtime");
var react_router_dom_1 = require("react-router-dom");
var react_1 = require("react");
var lucide_react_1 = require("lucide-react");
function Header() {
    var _a = (0, react_1.useState)(false), menuOpen = _a[0], setMenuOpen = _a[1];
    return ((0, jsx_runtime_1.jsxs)("header", { className: "sticky top-0 z-30 bg-white/80 backdrop-blur border-b border-blue-100 shadow-sm", children: [(0, jsx_runtime_1.jsxs)("div", { className: "max-w-5xl container mx-auto px-2 py-4 flex flex-col sm:flex-row sm:items-center sm:justify-between", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center justify-between w-full sm:w-auto", children: [(0, jsx_runtime_1.jsx)("span", { className: "text-2xl font-extrabold text-yellow-700 tracking-tight", children: "\uD83E\uDDEE MathThings!" }), (0, jsx_runtime_1.jsx)("button", { className: "sm:hidden p-2 rounded-md hover:bg-blue-50 transition-colors ml-2", "aria-label": "Toggle menu", onClick: function () { return setMenuOpen(function (v) { return !v; }); }, children: menuOpen ? (0, jsx_runtime_1.jsx)(lucide_react_1.X, { size: 24 }) : (0, jsx_runtime_1.jsx)(lucide_react_1.Menu, { size: 24 }) })] }), (0, jsx_runtime_1.jsxs)("nav", { className: "flex-col sm:flex-row flex gap-2 sm:gap-6 text-base font-medium items-center sm:items-center justify-center transition-all duration-200 ".concat(menuOpen ? 'flex' : 'hidden', " sm:flex"), children: [(0, jsx_runtime_1.jsx)(react_router_dom_1.Link, { to: "/", className: "px-6 py-2 rounded-lg font-bold text-lg shadow transition-colors focus:outline-none focus:ring-2 focus:ring-yellow-400 bg-yellow-600 hover:bg-yellow-700 text-white", children: "Home" }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Link, { to: "/map", className: "px-6 py-2 rounded-lg font-bold text-lg shadow transition-colors focus:outline-none focus:ring-2 focus:ring-yellow-400 bg-yellow-600 hover:bg-yellow-700 text-white", children: "Quest Map" }), (0, jsx_runtime_1.jsx)(react_router_dom_1.Link, { to: "/about", className: "px-6 py-2 rounded-lg font-bold text-lg shadow transition-colors focus:outline-none focus:ring-2 focus:ring-yellow-400 bg-yellow-600 hover:bg-yellow-700 text-white", children: "About" })] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "w-full bg-[#e8f0fe] text-yellow-800 text-base py-2 px-4 text-center border-b border-blue-100 shadow-sm", children: ["\uD83D\uDCF6 Our WiFi doesn't go on strike! Thank ", (0, jsx_runtime_1.jsx)("span", { className: "text-yellow-800 font-bold", children: "Nariza" }), " for hosting our \uD83E\uDDEE MathThings! party this month! \uD83E\uDD73"] })] }));
}
exports.default = Header;
